# Generated by Django 6.1.2 on 2026-10-08 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("phone", "Phone Call"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("locale", models.CharField(db_index=True, default="en", max_length=10)),
                ("page_path", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clicks",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inquiry Click",
                "verbose_name_plural": "Inquiry Clicks",
                "ordering": ["-created_at"],
            },
        ),
    ]
