# Generated by Django 6.1.2 on 2026-10-08 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Category name", max_length=150)),
                ("name_en", models.CharField(help_text="Category name", max_length=150, null=True)),
                ("name_am", models.CharField(help_text="Category name", max_length=150, null=True)),
                ("name_om", models.CharField(help_text="Category name", max_length=150, null=True)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, blank=True, max_length=160, unique=True),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Short description of the category"),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, help_text="Short description of the category", null=True
                    ),
                ),
                (
                    "description_am",
                    models.TextField(
                        blank=True, help_text="Short description of the category", null=True
                    ),
                ),
                (
                    "description_om",
                    models.TextField(
                        blank=True, help_text="Short description of the category", null=True
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="categories/")),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("title_en", models.CharField(blank=True, max_length=255, null=True)),
                ("title_am", models.CharField(blank=True, max_length=255, null=True)),
                ("title_om", models.CharField(blank=True, max_length=255, null=True)),
                ("image", models.ImageField(upload_to="gallery/")),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gallery_items",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Item",
                "verbose_name_plural": "Gallery Items",
                "ordering": ["sort_order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Customer facing identifier e.g. WC-001",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("name_am", models.CharField(max_length=255, null=True)),
                ("name_om", models.CharField(max_length=255, null=True)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True),
                ),
                ("description", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_am", models.TextField(blank=True, null=True)),
                ("description_om", models.TextField(blank=True, null=True)),
                (
                    "material",
                    models.CharField(
                        blank=True, help_text="e.g. Solid Mahogany, Oak veneer", max_length=200
                    ),
                ),
                (
                    "material_en",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Solid Mahogany, Oak veneer",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "material_am",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Solid Mahogany, Oak veneer",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "material_om",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Solid Mahogany, Oak veneer",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="e.g. Dark Walnut, Natural Teak", max_length=100
                    ),
                ),
                (
                    "color_en",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Dark Walnut, Natural Teak",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "color_am",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Dark Walnut, Natural Teak",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "color_om",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Dark Walnut, Natural Teak",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True,
                        help_text="Free text dimensions e.g. 210cm W x 90cm D x 75cm H",
                        max_length=150,
                    ),
                ),
                (
                    "is_customizable",
                    models.BooleanField(
                        default=True,
                        help_text="Allows customer to request custom dimensions/materials",
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("READY", "Ready to Deliver"),
                            ("MADE_TO_ORDER", "Made to Order"),
                            ("SOLD", "Previously Made / Sold"),
                        ],
                        db_index=True,
                        default="MADE_TO_ORDER",
                        max_length=20,
                    ),
                ),
                (
                    "lead_time",
                    models.CharField(
                        blank=True,
                        help_text="Production lead time e.g. '2-3 weeks' for Made-to-Order",
                        max_length=100,
                    ),
                ),
                (
                    "lead_time_en",
                    models.CharField(
                        blank=True,
                        help_text="Production lead time e.g. '2-3 weeks' for Made-to-Order",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "lead_time_am",
                    models.CharField(
                        blank=True,
                        help_text="Production lead time e.g. '2-3 weeks' for Made-to-Order",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "lead_time_om",
                    models.CharField(
                        blank=True,
                        help_text="Production lead time e.g. '2-3 weeks' for Made-to-Order",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "price_mode",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed Price"),
                            ("FROM", "Starting From"),
                            ("ASK", "Ask for Price"),
                        ],
                        default="ASK",
                        max_length=10,
                    ),
                ),
                (
                    "price_etb",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Price in Ethiopian Birr (ETB). Ignored if price_mode is ASK.",
                        null=True,
                    ),
                ),
                ("featured", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("seo_title_en", models.CharField(blank=True, max_length=255, null=True)),
                ("seo_title_am", models.CharField(blank=True, max_length=255, null=True)),
                ("seo_title_om", models.CharField(blank=True, max_length=255, null=True)),
                ("seo_description", models.TextField(blank=True)),
                ("seo_description_en", models.TextField(blank=True, null=True)),
                ("seo_description_am", models.TextField(blank=True, null=True)),
                ("seo_description_om", models.TextField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("telegram_posted_at", models.DateTimeField(blank=True, null=True)),
                ("telegram_message_id", models.CharField(blank=True, max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="products/")),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_primary", models.BooleanField(default=False)),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("alt_text_en", models.CharField(blank=True, max_length=255, null=True)),
                ("alt_text_am", models.CharField(blank=True, max_length=255, null=True)),
                ("alt_text_om", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Photo",
                "verbose_name_plural": "Product Photos",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
