# Generated by Django 6.1.2 on 2026-10-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='post_to_telegram',
            field=models.BooleanField(default=True, help_text='Broadcast to Telegram channel when published'),
        ),
    ]
