# Generated by Django 6.1.2 on 2026-10-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        default="+251911223344",
                        help_text="Format: +2519XXXXXXXX (international format without dashes or spaces for wa.me)",
                        max_length=50,
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        default="woodcarvo",
                        help_text="Telegram username without @ (e.g. woodcarvo)",
                        max_length=100,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        default="+251911223344",
                        help_text="Direct phone line for voice calls",
                        max_length=50,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="Bole Sub-city, Addis Ababa, Ethiopia", max_length=255
                    ),
                ),
                (
                    "address_en",
                    models.CharField(
                        blank=True,
                        default="Bole Sub-city, Addis Ababa, Ethiopia",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "address_am",
                    models.CharField(
                        blank=True,
                        default="Bole Sub-city, Addis Ababa, Ethiopia",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "address_om",
                    models.CharField(
                        blank=True,
                        default="Bole Sub-city, Addis Ababa, Ethiopia",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "google_maps_url",
                    models.URLField(
                        blank=True,
                        default="https://maps.google.com/?q=Addis+Ababa",
                        help_text="Direct Google Maps pin or search link",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, default=9.010793, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, default=38.761252, max_digits=9, null=True
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        blank=True,
                        default="Mon - Sat: 8:30 AM - 6:00 PM | Sun: Closed",
                        max_length=255,
                    ),
                ),
                (
                    "working_hours_en",
                    models.CharField(
                        blank=True,
                        default="Mon - Sat: 8:30 AM - 6:00 PM | Sun: Closed",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "working_hours_am",
                    models.CharField(
                        blank=True,
                        default="Mon - Sat: 8:30 AM - 6:00 PM | Sun: Closed",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "working_hours_om",
                    models.CharField(
                        blank=True,
                        default="Mon - Sat: 8:30 AM - 6:00 PM | Sun: Closed",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "instagram",
                    models.URLField(blank=True, default="https://instagram.com/woodcarvo"),
                ),
                ("facebook", models.URLField(blank=True, default="https://facebook.com/woodcarvo")),
                ("tiktok", models.URLField(blank=True, default="https://tiktok.com/@woodcarvo")),
                ("hero_image", models.ImageField(blank=True, null=True, upload_to="site/")),
                ("showroom_photo", models.ImageField(blank=True, null=True, upload_to="site/")),
                (
                    "about_text",
                    models.TextField(
                        blank=True,
                        help_text="Workshop heritage, master craftsperson story, and quality wood philosophy",
                    ),
                ),
                (
                    "about_text_en",
                    models.TextField(
                        blank=True,
                        help_text="Workshop heritage, master craftsperson story, and quality wood philosophy",
                        null=True,
                    ),
                ),
                (
                    "about_text_am",
                    models.TextField(
                        blank=True,
                        help_text="Workshop heritage, master craftsperson story, and quality wood philosophy",
                        null=True,
                    ),
                ),
                (
                    "about_text_om",
                    models.TextField(
                        blank=True,
                        help_text="Workshop heritage, master craftsperson story, and quality wood philosophy",
                        null=True,
                    ),
                ),
                (
                    "custom_furniture_text",
                    models.TextField(
                        blank=True,
                        help_text="Guide for clients commissioning bespoke custom furniture",
                    ),
                ),
                (
                    "custom_furniture_text_en",
                    models.TextField(
                        blank=True,
                        help_text="Guide for clients commissioning bespoke custom furniture",
                        null=True,
                    ),
                ),
                (
                    "custom_furniture_text_am",
                    models.TextField(
                        blank=True,
                        help_text="Guide for clients commissioning bespoke custom furniture",
                        null=True,
                    ),
                ),
                (
                    "custom_furniture_text_om",
                    models.TextField(
                        blank=True,
                        help_text="Guide for clients commissioning bespoke custom furniture",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site & Workshop Settings",
                "verbose_name_plural": "Site & Workshop Settings",
            },
        ),
    ]
