# Generated by Django 6.1.2 on 2026-10-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_number',
            field=models.CharField(default='+251910842430', help_text='Direct phone line for voice calls', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(default='+251910842430', help_text='Format: +2519XXXXXXXX (international format without dashes or spaces for wa.me)', max_length=50),
        ),
    ]
